### ISSUE TITLE
Fails to start with No Chat Reports

### ISSUE THREAD

**Issue by ryleu** [0x4e49434f4c45/amcdb#35] opened 2023-09-08 18:29 UTC
See title. It doesn't crash, it just flat out exits.

**Comment by 0x4e49434f4c45** [comment] 2023-09-08 23:22
I am assuming you mean this mod: https://modrinth.com/mod/no-chat-reports

I couldn't reproduce this issue on Minecraft 1.19.3 or 1.20.1. Can you provide logs or any other details on what you're seeing?

**Comment by 0x4e49434f4c45** [comment] 2023-09-13 05:04
Closing this issue as it could not be reproduced and no further information has been provided. Feel free to open another issue or comment on this one if you have additional details for investigation.

**Closed** 2023-09-13 05:05 UTC
